### ISSUE TITLE
Export type from projection

### ISSUE THREAD

**Issue by jmhmd** [plexinc/papr#123]
Is it possible to generate/export a type that is the result of a query with projection? I have a certain projection of a model that I use for a list format in the UI. I'd like to be able to create a new type/interface from that projection for type checking on the client. Thanks for this great library by the way!

**Comment by jmhmd** [comment]
After some digging into the source, I found `ProjectionType`, and did something like:

```js
export const caseListProjection = {
  user: 1,
  project: 1,
  shortid: 1,
  // studies: 1,
  "studies._id": 1,
  "studies.series.modality": 1,
  "studies.series._id": 1,
  "studies.studyDate": 1,
  "studies.uploadStatus": 1,
  "studies.description": 1,
  description: 1,
  folder: 1,
  diagnosis: 1,
  tags: 1,
  published: 1,
  meta: 1,
  customLinks: 1,
  createdAt: 1,
  updatedAt: 1,
};
type CaseDefinitionDocument_List = ProjectionType<CaseDefinitionDocument, typeof caseListProjection>
```

This appears to work as expected. One question I still have is if the dot notation subfields will project to the type definition correctly. Thanks again!

**Comment by avaly** [comment]
That's the correct usage of the `ProjectionType` type. We should add that in our docs.

Regarding the dot-notation support, unfortunately that's not supported right now. But once https://github.com/mongodb/node-mongodb-native/pull/2972 lands in mongodb, we should be able to use the same code to add support here as well.

**Comment by jmhmd** [comment]
That's great to hear, thanks!
