### ISSUE TITLE
Question aboout indexes...

### ISSUE THREAD

**Issue by age2pierre** [plexinc/papr#13]
Hello
We want to migrate from mongoose for a while and we're considering papr as an alternative.
One of the feature we use is the auto-indexing, what's the strategy you use at plex to manage those / what's the idiomatic way of doing it with papr ?
Thx

**Comment by avaly** [comment]
At Plex we use one-time migrations whenever we need to add/change/remove an index for a collection.

If we were to add such a feature inside Papr related to indexes, how would you see it working from an API point of view?

**Comment by jtassin** [comment]
I like the way mongoose is dealing with indexes.

```ts
animalSchema.index({ name: 1, type: -1 }); // schema level
```

I find it very convenient to read indexes with the model.

**Comment by italodeandra** [comment]
Can we reopen this? In my opinion this is really helpful (for those who don't want to do manual migrations for that).

**Comment by robertherber** [comment]
This feels like it would fit nicely with papr, it would feel great being able to specify indexes together with the schemas. Reopen?

**Comment by collier** [comment]
@avaly would you be able to share if Plex use a library to handle these one-time migrations? For example something like [migrate-mongo](https://github.com/seppevs/migrate-mongo)?

**Comment by avaly** [comment]
We are using an in-house migration runner at Plex. It's nothing complex, but it does handle background migrations in parallel & foreground migrations serially.
