### ISSUE TITLE
Problems reproducing the basic example

### ISSUE THREAD

**Issue by laurentenhoor** [plexinc/papr#130]
I cannot get the basic example running (without compiler errors). What am I doing wrong?

![image](https://user-images.githubusercontent.com/32955832/142604762-46bb6b26-a323-439a-ab76-6663e685af24.png)

**Comment by avaly** [comment]
I can't reproduce the error you're showing here. What versions of `mongodb` and `typescript` do you use?

**Comment by torbatian** [comment]
I also have the same problem with `mongodb` : `4.1.1` and `typescript` : `4.5.2` and `papr` : `2.1.1`

`Argument of type '[ObjectType<WithId<{ _id: ObjectId; age: number; firstName: string; lastName: string; }>>, Partial<{ _id: ObjectId; age: number; firstName: string; lastName: string; }>]' is not assignable to parameter of type '[BaseSchema, Partial<{ _id: ObjectId; age: number; firstName: string; lastName: string; }>]'.
  Type at position 0 in source is not compatible with type at position 0 in target.
    Type 'ObjectType<WithId<{ _id: ObjectId; age: number; firstName: string; lastName: string; }>>' is not assignable to type 'BaseSchema'.
      Property '_id' is optional in type 'ObjectType<WithId<{ _id: ObjectId; age: number; firstName: string; lastName: string; }>>' but required`

**Comment by avaly** [comment]
This error is most likely solved by enabling the `strictNullChecks` option in your `tsconfig.json`. See other discussion in https://github.com/plexinc/papr/issues/80#issuecomment-927912256

We'll add this information to our docs.
