### ISSUE TITLE
typescript 4.3.3 types problem 

### ISSUE THREAD

**Issue by reslear** [plexinc/papr#14]
<img width="1128" alt="Screenshot 2021-06-18 at 15 49 23" src="https://user-images.githubusercontent.com/12596485/122563504-f4e9ff80-d04c-11eb-9c1c-83d4fe2f2fdf.png">

[you site example](https://plexinc.github.io/papr/#/getting-started?id=define-a-model) have problem with types

**Comment by vanstinator** [comment]
You're likely missing a dependency in your package.json. The example project will throw this error when the dependencies aren't installed.

**Comment by reslear** [comment]
@vanstinator oh, problem in my `tsconfig.json` with include other local folders with d.ts files 
Excuse for troubling, thanks for the tip :)
