### ISSUE TITLE
`updateSchemas` should be called after all schemas are defined, not before them!

### ISSUE THREAD

**Issue by massivefermion** [plexinc/papr#151]
I recently joined a project that uses papr. It's a great tool. But the first time I looked at the example in the "about papr" section in https://plexinc.github.io/papr, my first reaction was, why are they calling `updateSchemas` before defining the schema? how can it update the schemas if no schemas are defined yet? Maybe I'm missing something?!

Anyway, I tested the sample code in both cases, calling `updateSchemas` before and after defining the schema and it seems that I'm right! When I call `updateSchemas` before defining the schema, no validation happens when I try to insert a document. Although I should say the type system is pretty robust and acts as a kind of validation but without it, you can insert a document that does not match the schema.

Only when I call `updateSchemas` after defining the schema, the validation actually works.
I should say that it's hard for me to believe that I'm the first one who noticed there might be a problem here so I'm not quite sure if I'm doing things right but I can't find any problem with what I did because I'm just using the sample code.

Is there really a problem or am I missing something?
Thanks

**Comment by ejmartin504** [comment]
You're absolutely correct! The sample code is a bit misleading. If you look elsewhere, the [docs](https://plexinc.github.io/papr/#/schema?id=schema-updates) clearly state that:

> Whenever a change is made to a papr schema, updateSchema will need to be called in order to update the JSON Schema validator on the collection.

But I agree, the sample code should be updated to reflect this (or at least we could add a comment)
