### ISSUE TITLE
Runtime validation solutions

### ISSUE THREAD

**Issue by rjombo** [plexinc/papr#237]
Hello! I'm in a need for client data validation solution. Tried zod but alas json-schema-to-zod package doesn't support runtime zod object generation only string code generation. I've found ajv + ajv-bsontype to work fine for validation. But unfortunately ajv-bsontype doesn't support data  modification wich would be nice to have (coercion to type; example: schema num - input str '4.11'  -> validation/coercion -> output num 4.11).  Also I was wondering what solution do you guys use at Plex?

**Comment by avaly** [comment]
We're not really using any client data validation solution.

We rely on the fact that the Mongo documents are validated accurately by the mongodb server.
