### ISSUE TITLE
more info about connect, disconnect in express 

### ISSUE THREAD

**Issue by reslear** [plexinc/papr#3]
hi, thank you for this library) 
its very great and simple, but i don't understand, near question:

1. How to use `connect` and `disconnect` in express server (Can connect once, and auto connect and auto disconnect if process.exit or express router `send()` )
2. Connect with mongoose parallel

i can create fork with express app example for you fix as correct.

have a good day 👍

**Comment by reslear** [comment]
2. found solution (maybe need add to doc)
```ts

const connect = (client: mongodb.MongoClient) => {
  papr.initialize(client.db('test'))
}

const connection = await mongoose.createConnection(url)
await connect(connection.getClient())
```

**Comment by avaly** [comment]
We already have this documented in: https://plexinc.github.io/papr/#/getting-started
