### ISSUE TITLE
Getting started page example is not validating at runtime

### ISSUE THREAD

**Issue by m-sureshraj** [plexinc/papr#30]
First of all, thank you for the library. It's a nice abstraction to add schema validation to MongoDB.

I used Papr's [getting started page](https://plexinc.github.io/papr/#/getting-started) example code to experiment, but it's not validating the `insert` or `update` operation at runtime. Also, I couldn't see any registered rules in the MongoDB compass UI.

![image](https://user-images.githubusercontent.com/12813750/124493030-c9983c00-ddd2-11eb-933f-5a91a44338c6.png)

You can use this [repository](https://github.com/m-sureshraj/papr-getting-started-example-issue) to reproduce the issue. 

Platform: Ubuntu 20.04.2 LTS
Node version: v14.15.0
MongoDB: mongo:4.4-bionic

**Comment by avaly** [comment]
You are correct. That code in the documentation is missing one important line: `await papr.updateSchemas();`

If you add this in your `connect()` function at the end, the insert will fail with a validation error.

**Comment by m-sureshraj** [comment]
That was quick :+1: Thanks! 
Yes, it fixed the issue. Here is the updated validation rule

![image](https://user-images.githubusercontent.com/12813750/124496508-2138a680-ddd7-11eb-8e51-bb58288d9062.png)
