### ISSUE TITLE
What should be the alternative solution for a mongoose populate?

### ISSUE THREAD

**Issue by baharalidurrani** [plexinc/papr#303]
## Background 
It's very well known to me that `papr` is a thin layer on the top of `mongodb` driver.

## But
What should be the recommended solution for the `mongoose.populate` method using `papr`?

## Expectation
An addition of a code snippet to the `docs` describing an alternative solution for mongoose populate using `mongodb joins` (or anything else) will be really helpful.

Thanks

**Comment by avaly** [comment]
There is no alternative to Mongoose's `populate`.

The Mongodb "join", the `$lookup` aggregate, is not fast at all, and is even recommended not to be used by Mongodb folks.

The real alternatives are:

1. Fetch data based on reference `ObjectId`s in our own application code.
2. Do not rely on normalized data. Use the [embedded sub-document pattern](https://www.mongodb.com/basics/embedded-mongodb) to avoid additional data lookups.
