### ISSUE TITLE
Intermittent `Error: Collection is not initialized!`

### ISSUE THREAD

**Issue by italodeandra** [plexinc/papr#309]
On the application start I connect to the MongoDB instance and run the `initialize` function before doing some migrations.

But some times I get this error `Error: Collection is not initialized!` other times I don't. It's intermittent.

What are the main reasons for this error to happen, even though my collection **was** initialized?

**Comment by CarlosLozanoHealthCaters** [comment]
Hi!

This error could happen if you are trying to access a collection before it has been initialised. A possibility is that you have a race condition in your code. Could you please share a snapshot of your code?

**Comment by italodeandra** [comment]
Hey, that makes sense. But it proved very difficult for me to detect what's causing the race condition.

I'm using Next.js and on every API call I'm calling and awaiting this `connectToDb` async function. To avoid race condition, I create a global that keeps the Promise of the connection so if any other API get's called at the same time, it should await for the Promise instead of calling the connect function again but maybe I'm doing something wrong.

This is the code if you want to check it out:

https://gist.github.com/italodeandra/c45c1fb419c8671c9db9da5376d8bef9

**Comment by CarlosLozanoHealthCaters** [comment]
I added some comments to your gist

**Comment by italodeandra** [comment]
It's been ages and I still have this problem. It doesn't happen with mongoose or the native driver. Is there any other suggestion of what might be causing it?

**Comment by avaly** [comment]
Can you provide a minimal reproduction case without next.js in the mix?

**Comment by italodeandra** [comment]
I'll try, but this issue seems to be specific to how Next.js create new instances of the same file (APIs) when you change them. It might be something related to race condition because that only happens on the start. And it is also intermittent. I usually just restart the app two or three times until it works.

**Comment by fiws** [comment]
Having the same problem with papr in a remix app. 

It's even worse in remix as the default setup has no easy way to do any kind of setup before the app starts and remix currently re-requires the whole app on every request.
This gets better if one opts into unstable remix features, but still occurs in "dev-mode" when the server restarts (every time).

Other database libraries get around this by queuing commands even tho the database connection is not ready yet. I think papr should also do this. Lots of dev headaches can be avoided that way.

I implemented my own hacky solution to this by wrapping all my papr models with a Proxy. You could try this @italodeandra 

### papr.ts (file that handles connection)

```ts
import { MongoClient } from "mongodb";
import Papr from "papr";

const papr = new Papr();
export let client: MongoClient;

const connection = (async () => {
  console.log("connecting to db");
  client = await MongoClient.connect(process.env.DATABASE_URL as string);
  papr.initialize(client.db());

  await papr.updateSchemas();
})();

export async function disconnect() {
  await client.close();
}

// readyProxy takes an object and returns a proxy that will wait for the
// database to be ready before executing any methods.
export function readyProxy<T extends object>(obj: T) {
  return new Proxy(obj, {
    get(target: any, prop) {
      // not a function, just return the value
      if (typeof target[prop] !== "function") {
        return target[prop];
      }

      // return a function that will wait for the database to be ready
      return async (...args: any[]) => {
        await connection;
        return target[prop](...args);
      };
    },
  }) as T;
}

export default papr;
```

`readyProxy` is the important part. It needs to be able to wait for the setup work (`await connection`)

### models/project.ts

Then wrap all models like this:

```ts
const Project = readyProxy(papr.model("projects", projectSchema));

export default Project;
```

**Comment by italodeandra** [comment]
Hey @fiws, thanks for the tip man.

I actually already use proxy for database connection, similar to what you did. It was actually one of the first things I tried, and the issue wasn't fixed. This intermittent error is not related to me not connecting before accessing a model, it might be something else I didn't find yet.

This also only happens with `papr`.

**Comment by italodeandra** [comment]
Almost one year later and I'm still having problems with this. But it's even worse now that I have several projects on production, this issue also happens on production on every release. So I need to restart the app until the collection actually initializes.

Is there anything magical I could try? I'm really out of options here. I'm not even sure this issue is specific to Papr.

**Comment by CarlosLozanoHealthCaters** [comment]
My suggestion here, it would be to try something like:
```
import Papr from "papr";
import { MongoClient } from "mongodb";

let _papr: Papr | undefined;
export function getPapr() {
  return _papr;
}

export async function connectToDb(
  databaseUri: string,
  databaseName: string
) {
  if(_papr !== undefined) {
    return;
  }

  _papr = new Papr();
  const client = await MongoClient.connect(databaseUri);
  const database = client.db(databaseName);
  _papr.initialize(database);
}
```

Then the function connectToDb() must be called when your are initiating Next server.

After that, you can use getPapr() function to create the models using the same instance that was created in the step before. 

What do you think?

**Comment by italodeandra** [comment]
> My suggestion here, it would be to try something like:
> 
> ```
> 
> import Papr from "papr";
> 
> import { MongoClient } from "mongodb";
> 
> 
> 
> let _papr: Papr | undefined;
> 
> export function getPapr() {
> 
>   return _papr;
> 
> }
> 
> 
> 
> export async function connectToDb(
> 
>   databaseUri: string,
> 
>   databaseName: string
> 
> ) {
> 
>   if(_papr !== undefined) {
> 
>     return;
> 
>   }
> 
> 
> 
>   _papr = new Papr();
> 
>   const client = await MongoClient.connect(databaseUri);
> 
>   const database = client.db(databaseName);
> 
>   _papr.initialize(database);
> 
> }
> 
> ```
> 
> 
> 
> Then the function connectToDb() must be called when your are initiating Next server.
> 
> 
> 
> After that, you can use getPapr() function to create the models using the same instance that was created in the step before. 
> 
> 
> 
> What do you think?

My current code is almost exactly like that. The only difference is that I a global instead of just a let. And I also don't use a custom server so I can't really run anything anywhere besides inside the API handler.

I also tried try-catching this error and forcing the database to be connected again but it also doesn't work. Somehow, as soon as it happens I can't use Papr anymore (it will always throw the same error).

I think this might have something to do with how Next bundles the project and keeps everything on the same file when deploying the endpoint. But even with this theory, I have no idea how to fix it.

**Comment by CarlosLozanoHealthCaters** [comment]
Most probable that's not enough. Try this:
Db file:
```typescript
import Papr from "papr";
import { MongoClient } from "mongodb";

let _papr: Papr | undefined;

export async function connectToDb(
  databaseUri: string,
  databaseName: string
) {
  if(_papr !== undefined) {
    return _papr;
  }

  _papr = new Papr();
  const client = await MongoClient.connect(databaseUri);
  const database = client.db(databaseName);
  _papr.initialize(database);

  return _papr;
}
```

Assets file:
```typescript
import { onlyServer } from "@italodeandra/next/utils/isServer";
import Papr, { schema, types, VALIDATION_ACTIONS, VALIDATION_LEVEL } from "papr";

const assetSchema = onlyServer(() =>
  schema(
    {
      offers: types.array(
        types.object({
          price: types.number({ required: true }),
          name: types.string(),
          createdAt: types.date({ required: true }),
          accepted: types.boolean(),
          repliedAt: types.date(),
        })
      ),
    },
    {
      timestamps: true,
      validationLevel: VALIDATION_LEVEL.OFF,
      validationAction: VALIDATION_ACTIONS.WARN,
    }
  )
);

export function getAsset(papr: Papr) {
  return papr.model("assets", assetSchema)
}
``` 

Your API file:
```typescript
import {getAsset} from "../../../collections/asset/Asset";
import { apiHandlerWrapper } from "@italodeandra/next/api/apiHandlerWrapper";
import connectToDb from "../../../db/db";

async function handler() {
  const papr = await connectToDb();
  const Asset = getAsset(papr); // This should solve the race condition

  return await Asset.find(
    {},
    {
      projection: {
        offers: 1,
      },
      sort: {
        updatedAt: -1,
      },
    }
  );
}

export default apiHandlerWrapper(handler);
```

**Comment by italodeandra** [comment]
This fixed it.
