### ISSUE TITLE
typescript error: Property '_id' is optional in type '<shema>' but required in type 'BaseSchema'

### ISSUE THREAD

**Issue by massivefermion** [plexinc/papr#359]
I'm trying to use papr with typescript but I'm getting a weird error that does not make any sense to me!
Just to make sure I wasn't doing anything wrong, I just tried the example in the home page:
```javascript
import { MongoClient } from 'mongodb';
import Papr, { schema, types } from 'papr';

const papr = new Papr();

const connection = await MongoClient.connect('mongodb://localhost:27017');
papr.initialize(connection.db('test'));

const User = papr.model('users', schema({
  age: types.number(),
  firstName: types.string({ required: true }),
  lastName: types.string({ required: true }),
}));

await papr.updateSchemas();

const johnWick = await User.find({ firstName: 'John', lastName: 'Wick' });
```
But when I type-check this code, I get:

> Argument of type '[{ age?: number; _id?: ObjectId; firstName?: string; lastName?: string; }, SchemaOptions<{ age: number; firstName: string; lastName: string; }>]' is not assignable to parameter of type '[BaseSchema, SchemaOptions<BaseSchema>]'.
>   Type at position 0 in source is not compatible with type at position 0 in target.
>     Type '{ age?: number; _id?: ObjectId; firstName?: string; lastName?: string; }' is not assignable to type 'BaseSchema'.
>       Property '_id' is optional in type '{ age?: number; _id?: ObjectId; firstName?: string; lastName?: string; }' but required in type 'BaseSchema'.

Which is weird, because when I looked at the code for the schema function, it's actually adding the `_id` field to the schema. But I added `_id: types.objectId({ required: true })` to the schema anyway and this time I got:

> Argument of type '[{ age?: number; _id?: ObjectId; firstName?: string; lastName?: string; }, SchemaOptions<{ _id: ObjectId; age: number; firstName: string; lastName: string; }>]' is not assignable to parameter of type '[BaseSchema, SchemaOptions<{ _id: ObjectId; age: number; firstName: string; lastName: string; }>]'.
>   Type at position 0 in source is not compatible with type at position 0 in target.
>     Type '{ age?: number; _id?: ObjectId; firstName?: string; lastName?: string; }' is not assignable to type 'BaseSchema'.
>       Property '_id' is optional in type '{ age?: number; _id?: ObjectId; firstName?: string; lastName?: string; }' but required in type 'BaseSchema'.

So even when I explicitly added a required `_id` field, I still got the typescript error.
what should I do?
thanks

**Comment by CarlosLozanoHealthCaters** [comment]
Hi!

Have you enabled [strictNullChecks](https://www.typescriptlang.org/tsconfig#strictNullChecks) option in the TypeScript configuration?

**Comment by massivefermion** [comment]
I just enabled it and the issue was totally fixed. Thanks.
