### ISSUE TITLE
Own dot-notation filter types

### ISSUE THREAD

**Issue by avaly** [plexinc/papr#410]
The MongoDB team is planning to remove the default dot-notation support from the `Filter` type in the upcoming v5 of the driver.

See: https://github.com/mongodb/node-mongodb-native/pull/3520

We want to adopt those types inside `Papr`, in order to keep Papr filters type safe.

**Comment by CarlosLozanoHealthCaters** [comment]
Although they are removing dot-notation support from the Filter, they are also creating a new experimental type StrictFilter that keep the dot-notation.

What do you think if we try to convince them to implement a StrictRootFilterOperators too and encourage them to use it in the StrictFilter?

That would solve all our issues, right?

**Comment by avaly** [comment]
https://github.com/mongodb/node-mongodb-native/pull/3520#issuecomment-1402140927

I would rather not use their `StrictFilter` types, since they still mix in `Document` in there. So we'd like to bring those types into Papr and own them. We can definitely follow the upstream changes and bring in improvements as they come in there.

**Comment by CarlosLozanoHealthCaters** [comment]
MongoDB has released the v5.0.0 of Node driver with the StrictFilter changes (https://github.com/mongodb/node-mongodb-native/releases)
