### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by Billcountry** [plexinc/papr#457]
Every time I call `model.findById` or `model.findOne` I get a typescript error: `Type instantiation is excessively deep and possibly infinite`

Type of property '[species]' circularly references itself in mapped type '{ [HeadKey in keyof SharedArrayBuffer]: DeepPick<SharedArrayBuffer[HeadKey], InnerKeys<HeadKey, string>>; }'.

**Comment by avaly** [comment]
That error message you posted points out to a circular reference in your schema. Papr does not support circular references in schemas.

Please re-open, if that's not the case, and post your schema definition.
