### ISSUE TITLE
Add findOneAndDelete operation?

### ISSUE THREAD

**Issue by JoshuaWise** [plexinc/papr#57]
I'd like to use Papr for a project at the company I work for, but I need to use the [`findOneAndDelete()`](http://mongodb.github.io/node-mongodb-native/4.0/classes/collection.html#findoneanddelete) operation, which doesn't appear to be supported by Papr. Could this be added?

**Comment by muco-rolle** [comment]
I think it has  a `deleteOne` function that accomplishes the same thing

**Comment by JoshuaWise** [comment]
They're not the same. `findOneAndDelete()` deletes a document and returns the deleted document in one atomic operation.

**Comment by muco-rolle** [comment]
Anyone working on this?

**Comment by avaly** [comment]
Not yet. We'll gladly accept a PR for this. Otherwise it'll take a few more days on our part to add it.

**Comment by muco-rolle** [comment]
I'm willing to work on it, as I'm new to Typescript and Open source in general I would need some guidance.

**Comment by avaly** [comment]
Published in papr@2.1.0
