### ISSUE TITLE
Loosen up (or upgrade) mongodb peer dependency

### ISSUE THREAD

**Issue by robertherber** [plexinc/papr#573]
I'm getting type errors when calling `papr.initialize(db)` since papr peerDepends on version 5 of MongoDB, and the latest MongoDB is 6.

If there's nothing stopping it I think the best would be to loosen up the peerDependency version. I guess the only potential stopper would be if there's been changes to the updateSchema logic?

My current workaround is to add a resolutions to my package.json:
```
"resolutions": {
  "mongodb": "^6.0.0"
}
```

**Comment by avaly** [comment]
There are actually breaking changes in MongoDB V6, so the peer version limitation is actually a good thing. We have a PR ready for updating to MongoDB v6, which will land shortly next week.

**Comment by robertherber** [comment]
@avaly Cool, gotcha! 👍

**Comment by avaly** [comment]
v15.0.0 is out now with support for mongodb v6.*
