### ISSUE TITLE
Can't use upsert inside transaction

### ISSUE THREAD

**Issue by MarceloPeresToi** [plexinc/papr#707]
Is there any specific reason why the upsert method does not allow options?
I would like to pass my session into it but I can't.
I would assume it would accept the same options as update, right?

<img width="876" alt="Screenshot 2024-01-17 at 13 58 05" src="https://github.com/plexinc/papr/assets/47488659/1853dd99-33ee-4154-b1c5-3fadc93ffd55">

**Comment by joshuat** [comment]
This is definitely something that could be improved - until this is done, though, you should be able to use `model.findOneAndUpdate` with `{ upsert: true }` in the options to achieve the same functionality.

**Comment by MarceloPeresToi** [comment]
Oh, that's right!
My first instinct was to try the `updateOne` method, but it doesn't accept the upsert option.
I didn't realise there was a `findOneAndUpdate`. Thanks!
BTW, what's the difference between `findOneAndUpdate` and `updateOne`?

**Comment by joshuat** [comment]
`findOneAndUpdate` does a find operation and updates the record, returning a document - `updateOne` only does an update operation and returns the update result.

**Comment by MarceloPeresToi** [comment]
Makes sense! Thanks for the help!
