### ISSUE TITLE
`oneOf` removes `null` type

### ISSUE THREAD

**Issue by jvvan** [plexinc/papr#715]
If we have the following schema:
```ts
const schema= schema({
  stringOrNull: types.oneOf([types.string(), types.null()], {
    required: true,
  }),
});
```

`stringOrNull` has `string` type instead of `string | null`.

This is caused because of the `NonNullable` type [here](https://github.com/plexinc/papr/blob/3d3001b0cac6819a7abd700d3c4b0882743fad3f/src/types.ts#L216).

Tried `Exclude<Types[number], undefined>` instead and it seems to work how it's supposed to.

**Comment by joshuat** [comment]
This is a great catch and would make an awesome contribution if you have the time for it.

You can find the contributing guidelines [here](https://github.com/plexinc/papr/blob/main/CONTRIBUTING.md) and make sure to include a test case highlighting the issue to prevent a future regression.
