### ISSUE TITLE
How to change verbosity logging?

### ISSUE THREAD

**Issue by djdembeck** [plexinc/papr#82]
I am looking for a way to not log insertOne results in my NodeJs application log. How is this accomplished in Papr? From the Mongo docs, there I think I would use `db.setLogLevel()`, but I don't see that method in Papr or in it's docs.

Thanks for this tool!

**Comment by avaly** [comment]
When you initialize Papr, you use a MongoDB `db` instance:

```js
const db = connection.db('test');
papr.initialize(db);
```

You can call any methods available on the MongoDB `db` instance, including the `setLogLevel`.

**Comment by djdembeck** [comment]
Sorry, I'm not following. I tried all manner of combinations I couldn't get that working. I'm using the default `papr.ts` from the docs. Here's all that I tried without success:
```
export async function connect () {
    client = await MongoClient.connect(uri)

    papr.initialize(client.db('audnexus'))

    db().setLogLevel(1)
    db.setLogLevel(1)
    client.db.setLogLevel(1)
    client.db().setLogLevel(1)
    papr.setLogLevel(1)
    client.setLogLevel(1)
    papr.db().setLogLevel(1)
    papr.db.setLogLevel(1)

    await papr.updateSchemas()
}
```

**Comment by avaly** [comment]
Try this:

```ts
export async function connect () {
    client = await MongoClient.connect(uri)

	const db = client.db('audnexus')

    papr.initialize(db)

    db.setLogLevel(1)

    await papr.updateSchemas()
}
```

**Comment by djdembeck** [comment]
Thanks for the quick replies!

That sadly doesn't work for me:
```
[Node] (node:214746) UnhandledPromiseRejectionWarning: TypeError: db.setLogLevel is not a function
[Node]     at connect (/home/djdembeck/projects/audnexus/dist/config/papr.js:15:8)
[Node]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[Node]     at async /home/djdembeck/projects/audnexus/dist/server.js:25:5
```

**Comment by avaly** [comment]
Please refer to the [mongodb docs](https://mongodb.github.io/node-mongodb-native/4.0/) for help on those methods - they are not from within Papr.
