### ISSUE TITLE
Add Decimal128 type support

### ISSUE THREAD

**Issue by djdembeck** [plexinc/papr#94]
I noticed Papr has no means of storing decimal types, which both mongoose and MongoDB (since 3.4) support:
https://mongoosejs.com/docs/api.html#mongoose_Mongoose-Decimal128
https://docs.mongodb.com/upcoming/release-notes/3.4/#decimal-type

**Comment by geovla93** [comment]
It would be great if this was added.

**Comment by avaly** [comment]
We'll happily accept a PR for this feature.

**Comment by nholik** [comment]
@avaly this seemed pretty straightforward, so I took a stab at it.
