### ISSUE TITLE
Nested documents: how do you control whether or not an _id field is added or not?

### ISSUE THREAD

**Issue by tom-thorne** [plexinc/papr#954]
I am porting from mongoose, and I am wondering how to represent this mongoose schema in papr (below), where there is a subdocument, but the subdocument _id field has been suppressed.

I can't find any documentation on this

**MONGOOSE**
```
const mongooseSchema: Schema = new Schema({
    segmentId: { type: Schema.Types.ObjectId, required: true },
    userId: { type: Schema.Types.ObjectId, required: true },
    source: new Schema({
        definitionId: {
            type: String,
            required: false
        },
        ruleId: {
            type: String,
            required: false
        }
    }, { _id: false }), // < =====  how do I control the _id field like this in papr?
});
```

**PAPR**
```
export const paprSchema = schema(
    {
        segmentId: types.objectId({ required: true }),
        userId: types.objectId({ required: true }),
        expires: types.date({ required: false }),
        source: types.object(
            {
                // is an _id field added automatically ?  if so, how to turn it off
                definitionId: types.string({ required: false }),
                ruleId: types.string({ required: false }),
            },
            { required: false }
        )
    }
);

```
So my questions are:
* is an _id field added automatically ?  
* if yes, how to turn it off
* if not, how to add one that is auto added on insert?

Thanks for a great package!

**Comment by avaly** [comment]
> is an _id field added automatically

No, we don't add one automatically. That feature is a Mongoose feature. We think it's wrong as a ORM/library to make these changes to your data on your behalf.

> how to add one that is auto added on insert

You can just create a `new ObjectId()` and put in your data when you insert a new document.

**Comment by tom-thorne** [comment]
Just to clarify: does papr auto add an _id in any circumstances, for instance when the top level document is added?

**Comment by avaly** [comment]
> does papr auto add an _id in any circumstances, for instance when the top level document is added?

No. Papr does not add any `_id`. If you insert a document without an `_id`, the MongoDB server itself will assign it an `_id`.
