### ISSUE TITLE
Allow 'upsert' in updateOne options 

### ISSUE THREAD

**Issue by tom-thorne** [plexinc/papr#970]
AFAIK, the mongodb client supports updateOne `upsert`.

However, at the moment `upsert` is explicitly excluded from `updateOne` options.  I am not sure why this is.

It would be useful if it were allowed, since it is the only upsert method returns whether or not the record was updated or inserted.

**Comment by avaly** [comment]
Papr has a separate [`upsert` method](https://plexinc.github.io/papr/#/api/model?id=upsert).

**Comment by tom-thorne** [comment]
Unfortunately the separate `upsert` method doesn't have the return type I am looking for (upserted / updated count).  It just returns a before or after doc
